apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxpayer-service
  namespace: tax-modernization
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: taxpayer-service
  template:
    metadata:
      labels:
        app: taxpayer-service
    spec:
      containers:
      - name: taxpayer-service
        image: taxpayer-service:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: taxpayer-service
  namespace: tax-modernization
spec:
  selector:
    app: taxpayer-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP